# Generated by Django 4.2.16 on 2024-11-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_scrapped',
            field=models.BooleanField(default=False),
        ),
    ]
